name: update_prices

on:
  schedule:
    # Запуск каждые 5 минут
    - cron: '1 * * * *'
  # workflow-dispatch:

jobs:
  my-job:
    name: Price checking
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo "Hello World"