name: update_prices
run-name: Обновление цен на отслеживаемые товары...
on:
  schedule:
    # Запуск каждые 5 минут
    - cron: '1 * * * *'
  workflow-dispatch:
jobs:
  build:
    name: Price checking
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo "Hello World"